// Globalisor — Presentation Demo Seed Data

export const USERS = [
    { user_id: 'U001', full_name: 'Alex Administrator', email: 'admin@globalisor.com', phone: '+65 8111 0001', role: 'admin', status: 'active', avatar_color: '#0055a4', initials: 'AA', created_at: '2025-10-01' },
    { user_id: 'U002', full_name: 'Sarah Lim', email: 'staff1@globalisor.com', phone: '+65 8222 0001', role: 'staff', status: 'active', avatar_color: '#7c3aed', initials: 'SL', created_at: '2025-10-05' },
    { user_id: 'U003', full_name: 'James Tan', email: 'staff2@globalisor.com', phone: '+65 8333 0002', role: 'staff', status: 'active', avatar_color: '#059669', initials: 'JT', created_at: '2025-10-05' },
    { user_id: 'U004', full_name: 'Kevin Wong', email: 'staff3@globalisor.com', phone: '+65 8444 0003', role: 'staff', status: 'active', avatar_color: '#d97706', initials: 'KW', created_at: '2025-10-05' },
    { user_id: 'U005', full_name: 'Ethan Tan', email: 'user1@globalisor.com', phone: '+65 9111 0001', role: 'client', status: 'active', avatar_color: '#0891b2', initials: 'ET', created_at: '2026-01-10' },
    { user_id: 'U006', full_name: 'Priya Sharma', email: 'user2@globalisor.com', phone: '+65 9222 0002', role: 'client', status: 'active', avatar_color: '#7c3aed', initials: 'PS', created_at: '2026-01-15' },
    { user_id: 'U007', full_name: 'Ahmed Hassan', email: 'user3@globalisor.com', phone: '+65 9333 0003', role: 'client', status: 'active', avatar_color: '#059669', initials: 'AH', created_at: '2026-01-22' },
    { user_id: 'U008', full_name: 'Sophia Liu', email: 'user4@globalisor.com', phone: '+65 9444 0004', role: 'client', status: 'active', avatar_color: '#dc2626', initials: 'SL', created_at: '2026-02-01' },
    { user_id: 'U009', full_name: 'Marcus Ng', email: 'marcus@client.com', phone: '+65 9555 0005', role: 'client', status: 'active', avatar_color: '#0a2340', initials: 'MN', created_at: '2026-02-10' },
    { user_id: 'U010', full_name: 'Lin Wei', email: 'linwei@client.com', phone: '+65 9666 0006', role: 'client', status: 'active', avatar_color: '#b45309', initials: 'LW', created_at: '2026-02-14' },
    { user_id: 'U011', full_name: 'Ravi Kumar', email: 'ravi@client.com', phone: '+65 9777 0007', role: 'client', status: 'active', avatar_color: '#0e7490', initials: 'RK', created_at: '2026-02-20' },
    { user_id: 'U012', full_name: 'Mei Ling Chua', email: 'meiling@client.com', phone: '+65 9888 0008', role: 'client', status: 'active', avatar_color: '#be185d', initials: 'MC', created_at: '2026-03-01' },
];

export const APPLICATIONS = [
    { application_id: 'APP-1001', client_user_id: 'U005', assigned_staff_id: 'U002', application_type: 'Company Incorporation', business_name: 'LionPath Trading Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'International Trade & Commerce', registered_address: '71 Robinson Road #14-01, Singapore 068895', share_capital: 10000, share_currency: 'SGD', status: 'In Progress', priority: 'High', acra_ref_number: null, submitted_at: '2026-01-12', completed_at: null, created_at: '2026-01-12', updated_at: '2026-03-05' },
    { application_id: 'APP-1002', client_user_id: 'U006', assigned_staff_id: 'U002', application_type: 'Company Incorporation', business_name: 'Merlion Ventures Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Venture Capital & Investment', registered_address: '1 Raffles Place #20-01, Singapore 048616', share_capital: 50000, share_currency: 'SGD', status: 'Completed', priority: 'Normal', acra_ref_number: 'ACRA-202601-00421', submitted_at: '2026-01-18', completed_at: '2026-02-15', created_at: '2026-01-18', updated_at: '2026-02-15' },
    { application_id: 'APP-1003', client_user_id: 'U007', assigned_staff_id: 'U003', application_type: 'Company Incorporation', business_name: 'Marina Bay Foods Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Food & Beverage Manufacturing', registered_address: '18 Cross Street #12-01, Singapore 048423', share_capital: 5000, share_currency: 'SGD', status: 'KYC Review', priority: 'Normal', acra_ref_number: null, submitted_at: '2026-02-03', completed_at: null, created_at: '2026-02-03', updated_at: '2026-03-06' },
    { application_id: 'APP-1004', client_user_id: 'U008', assigned_staff_id: 'U003', application_type: 'Company Incorporation', business_name: 'SkyBridge Consulting Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Management Consulting', registered_address: '10 Anson Road #05-01, Singapore 079903', share_capital: 2000, share_currency: 'SGD', status: 'Submitted to ACRA', priority: 'Normal', acra_ref_number: 'ACRA-202602-00887', submitted_at: '2026-02-10', completed_at: null, created_at: '2026-02-10', updated_at: '2026-03-04' },
    { application_id: 'APP-1005', client_user_id: 'U009', assigned_staff_id: 'U004', application_type: 'Company Incorporation', business_name: 'Orchid Bloom Retail Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Retail & E-Commerce', registered_address: '313 Orchard Road #04-01, Singapore 238895', share_capital: 3000, share_currency: 'SGD', status: 'Pending Documents', priority: 'Normal', acra_ref_number: null, submitted_at: '2026-02-15', completed_at: null, created_at: '2026-02-15', updated_at: '2026-03-07' },
    { application_id: 'APP-1006', client_user_id: 'U010', assigned_staff_id: 'U004', application_type: 'Company Incorporation', business_name: 'RedDot Ventures Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Technology Startup & Innovation', registered_address: '79 Anson Road #23-01, Singapore 079906', share_capital: 100000, share_currency: 'SGD', status: 'Completed', priority: 'High', acra_ref_number: 'ACRA-202602-01103', submitted_at: '2026-02-20', completed_at: '2026-03-08', created_at: '2026-02-20', updated_at: '2026-03-08' },
    { application_id: 'APP-1007', client_user_id: 'U011', assigned_staff_id: 'U002', application_type: 'Company Incorporation', business_name: 'HarbourEdge Logistics Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Logistics & Supply Chain', registered_address: '3 Gateway Drive #18-01, Singapore 608532', share_capital: 8000, share_currency: 'SGD', status: 'In Progress', priority: 'Emergency', acra_ref_number: null, submitted_at: '2026-02-25', completed_at: null, created_at: '2026-02-25', updated_at: '2026-03-08' },
    { application_id: 'APP-1008', client_user_id: 'U012', assigned_staff_id: 'U003', application_type: 'Company Incorporation', business_name: 'UrbanCore Services Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Property Management & Services', registered_address: '438 Alexandra Road #12-01, Singapore 119958', share_capital: 5000, share_currency: 'SGD', status: 'New', priority: 'Normal', acra_ref_number: null, submitted_at: null, completed_at: null, created_at: '2026-03-05', updated_at: '2026-03-05' },
    { application_id: 'APP-1009', client_user_id: 'U005', assigned_staff_id: 'U004', application_type: 'Company Incorporation', business_name: 'PeakTech Solutions Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Software Development', registered_address: '5 Science Park Drive, Singapore 118269', share_capital: 20000, share_currency: 'SGD', status: 'KYC Review', priority: 'High', acra_ref_number: null, submitted_at: '2026-03-01', completed_at: null, created_at: '2026-03-01', updated_at: '2026-03-08' },
    { application_id: 'APP-1010', client_user_id: 'U006', assigned_staff_id: 'U002', application_type: 'Company Incorporation', business_name: 'GreenPath Eco Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Environmental Consulting', registered_address: '25 International Business Park, Singapore 609916', share_capital: 15000, share_currency: 'SGD', status: 'Submitted to ACRA', priority: 'Normal', acra_ref_number: 'ACRA-202603-00214', submitted_at: '2026-03-02', completed_at: null, created_at: '2026-03-02', updated_at: '2026-03-08' },
    { application_id: 'APP-1011', client_user_id: 'U007', assigned_staff_id: 'U003', application_type: 'Company Incorporation', business_name: 'AsiaLink Finance Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Financial Advisory', registered_address: '6 Shenton Way #28-01, Singapore 068809', share_capital: 30000, share_currency: 'SGD', status: 'In Progress', priority: 'High', acra_ref_number: null, submitted_at: '2026-03-03', completed_at: null, created_at: '2026-03-03', updated_at: '2026-03-08' },
    { application_id: 'APP-1012', client_user_id: 'U008', assigned_staff_id: 'U004', application_type: 'Company Incorporation', business_name: 'NovaMed Health Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Healthcare & Medical Services', registered_address: '11 Outram Road, Singapore 169078', share_capital: 25000, share_currency: 'SGD', status: 'Pending Documents', priority: 'Normal', acra_ref_number: null, submitted_at: '2026-03-04', completed_at: null, created_at: '2026-03-04', updated_at: '2026-03-07' },
    { application_id: 'APP-1013', client_user_id: 'U009', assigned_staff_id: 'U002', application_type: 'Company Incorporation', business_name: 'CityScape Properties Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Real Estate Development', registered_address: '9 Paya Lebar Road #08-01, Singapore 409041', share_capital: 200000, share_currency: 'SGD', status: 'New', priority: 'High', acra_ref_number: null, submitted_at: null, completed_at: null, created_at: '2026-03-06', updated_at: '2026-03-06' },
    { application_id: 'APP-1014', client_user_id: 'U010', assigned_staff_id: 'U003', application_type: 'Company Incorporation', business_name: 'DigitalFirst Media Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Digital Marketing & Media', registered_address: '140 Robinson Road #08-01, Singapore 068907', share_capital: 5000, share_currency: 'SGD', status: 'KYC Review', priority: 'Normal', acra_ref_number: null, submitted_at: '2026-03-07', completed_at: null, created_at: '2026-03-07', updated_at: '2026-03-08' },
    { application_id: 'APP-1015', client_user_id: 'U011', assigned_staff_id: 'U004', application_type: 'Company Incorporation', business_name: 'SentosaEdge Tourism Pte. Ltd.', business_type: 'Private Limited (Pte. Ltd.)', nature_of_business: 'Tourism & Hospitality', registered_address: '8 Sentosa Gateway, Singapore 098269', share_capital: 10000, share_currency: 'SGD', status: 'New', priority: 'Normal', acra_ref_number: null, submitted_at: null, completed_at: null, created_at: '2026-03-08', updated_at: '2026-03-08' },
];

export const KYC_RECORDS = [
    { kyc_id: 'KYC-001', application_id: 'APP-1001', client_user_id: 'U005', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U002', reviewed_at: '2026-01-20', remarks: 'All checks passed', created_at: '2026-01-12', updated_at: '2026-01-20' },
    { kyc_id: 'KYC-002', application_id: 'APP-1002', client_user_id: 'U006', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U002', reviewed_at: '2026-01-25', remarks: 'Completed', created_at: '2026-01-18', updated_at: '2026-01-25' },
    { kyc_id: 'KYC-003', application_id: 'APP-1003', client_user_id: 'U007', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Under Review', address_verification_status: 'Pending', overall_kyc_status: 'Under Review', reviewed_by_staff_id: 'U003', reviewed_at: null, remarks: 'Awaiting address proof', created_at: '2026-02-03', updated_at: '2026-03-06' },
    { kyc_id: 'KYC-004', application_id: 'APP-1004', client_user_id: 'U008', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U003', reviewed_at: '2026-02-18', remarks: 'All clear', created_at: '2026-02-10', updated_at: '2026-02-18' },
    { kyc_id: 'KYC-005', application_id: 'APP-1005', client_user_id: 'U009', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Pending', overall_kyc_status: 'Under Review', reviewed_by_staff_id: 'U004', reviewed_at: null, remarks: 'Missing address proof', created_at: '2026-02-15', updated_at: '2026-03-07' },
    { kyc_id: 'KYC-006', application_id: 'APP-1006', client_user_id: 'U010', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U004', reviewed_at: '2026-02-26', remarks: 'Passed', created_at: '2026-02-20', updated_at: '2026-02-26' },
    { kyc_id: 'KYC-007', application_id: 'APP-1007', client_user_id: 'U011', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U002', reviewed_at: '2026-03-01', remarks: 'Approved — flagged for fast-track', created_at: '2026-02-25', updated_at: '2026-03-01' },
    { kyc_id: 'KYC-008', application_id: 'APP-1008', client_user_id: 'U012', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Pending', address_verification_status: 'Pending', overall_kyc_status: 'Pending', reviewed_by_staff_id: null, reviewed_at: null, remarks: '', created_at: '2026-03-05', updated_at: '2026-03-05' },
    { kyc_id: 'KYC-009', application_id: 'APP-1009', client_user_id: 'U005', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Under Review', address_verification_status: 'Under Review', overall_kyc_status: 'Under Review', reviewed_by_staff_id: 'U004', reviewed_at: null, remarks: 'Director ID needs clarity', created_at: '2026-03-01', updated_at: '2026-03-08' },
    { kyc_id: 'KYC-010', application_id: 'APP-1010', client_user_id: 'U006', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U002', reviewed_at: '2026-03-05', remarks: 'Cleared', created_at: '2026-03-02', updated_at: '2026-03-05' },
    { kyc_id: 'KYC-011', application_id: 'APP-1011', client_user_id: 'U007', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Approved', overall_kyc_status: 'Approved', reviewed_by_staff_id: 'U003', reviewed_at: '2026-03-06', remarks: 'OK', created_at: '2026-03-03', updated_at: '2026-03-06' },
    { kyc_id: 'KYC-012', application_id: 'APP-1012', client_user_id: 'U008', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Approved', address_verification_status: 'Rejected', overall_kyc_status: 'Rejected', reviewed_by_staff_id: 'U004', reviewed_at: '2026-03-06', remarks: 'Address proof invalid — resubmit required', created_at: '2026-03-04', updated_at: '2026-03-06' },
    { kyc_id: 'KYC-013', application_id: 'APP-1013', client_user_id: 'U009', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Pending', address_verification_status: 'Pending', overall_kyc_status: 'Pending', reviewed_by_staff_id: null, reviewed_at: null, remarks: '', created_at: '2026-03-06', updated_at: '2026-03-06' },
    { kyc_id: 'KYC-014', application_id: 'APP-1014', client_user_id: 'U010', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Under Review', address_verification_status: 'Pending', overall_kyc_status: 'Under Review', reviewed_by_staff_id: 'U003', reviewed_at: null, remarks: 'Awaiting documents', created_at: '2026-03-07', updated_at: '2026-03-08' },
    { kyc_id: 'KYC-015', application_id: 'APP-1015', client_user_id: 'U011', pep_status: 'Clear', sanctions_check_status: 'Clear', identity_verification_status: 'Pending', address_verification_status: 'Pending', overall_kyc_status: 'Pending', reviewed_by_staff_id: null, reviewed_at: null, remarks: '', created_at: '2026-03-08', updated_at: '2026-03-08' },
];

export const DOCUMENTS = [
    { document_id: 'DOC-001', application_id: 'APP-1001', uploaded_by_user_id: 'U005', document_type: 'Passport', file_name: 'ethan_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: 'Valid', uploaded_at: '2026-01-13', reviewed_at: '2026-01-15' },
    { document_id: 'DOC-002', application_id: 'APP-1001', uploaded_by_user_id: 'U005', document_type: 'Address Proof', file_name: 'ethan_address.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: 'Clear', uploaded_at: '2026-01-13', reviewed_at: '2026-01-16' },
    { document_id: 'DOC-003', application_id: 'APP-1001', uploaded_by_user_id: 'U005', document_type: 'Director ID', file_name: 'ethan_director_id.pdf', file_url: '#', review_status: 'Pending', reviewed_by_user_id: null, review_comments: '', uploaded_at: '2026-03-04', reviewed_at: null },
    { document_id: 'DOC-004', application_id: 'APP-1002', uploaded_by_user_id: 'U006', document_type: 'Passport', file_name: 'priya_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: '', uploaded_at: '2026-01-19', reviewed_at: '2026-01-22' },
    { document_id: 'DOC-005', application_id: 'APP-1002', uploaded_by_user_id: 'U006', document_type: 'Address Proof', file_name: 'priya_address.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: '', uploaded_at: '2026-01-19', reviewed_at: '2026-01-22' },
    { document_id: 'DOC-006', application_id: 'APP-1002', uploaded_by_user_id: 'U006', document_type: 'Business Supporting Document', file_name: 'merlion_biz_plan.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: '', uploaded_at: '2026-01-20', reviewed_at: '2026-01-23' },
    { document_id: 'DOC-007', application_id: 'APP-1003', uploaded_by_user_id: 'U007', document_type: 'Passport', file_name: 'ahmed_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U003', review_comments: '', uploaded_at: '2026-02-04', reviewed_at: '2026-02-08' },
    { document_id: 'DOC-008', application_id: 'APP-1003', uploaded_by_user_id: 'U007', document_type: 'Address Proof', file_name: 'ahmed_address.pdf', file_url: '#', review_status: 'Pending', reviewed_by_user_id: null, review_comments: 'Blurry — request reupload', uploaded_at: '2026-02-04', reviewed_at: null },
    { document_id: 'DOC-009', application_id: 'APP-1004', uploaded_by_user_id: 'U008', document_type: 'Passport', file_name: 'sophia_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U003', review_comments: '', uploaded_at: '2026-02-11', reviewed_at: '2026-02-14' },
    { document_id: 'DOC-010', application_id: 'APP-1004', uploaded_by_user_id: 'U008', document_type: 'Address Proof', file_name: 'sophia_address.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U003', review_comments: '', uploaded_at: '2026-02-11', reviewed_at: '2026-02-14' },
    { document_id: 'DOC-011', application_id: 'APP-1005', uploaded_by_user_id: 'U009', document_type: 'Passport', file_name: 'marcus_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U004', review_comments: '', uploaded_at: '2026-02-16', reviewed_at: '2026-02-19' },
    { document_id: 'DOC-012', application_id: 'APP-1005', uploaded_by_user_id: 'U009', document_type: 'Address Proof', file_name: 'marcus_address.pdf', file_url: '#', review_status: 'Rejected', reviewed_by_user_id: 'U004', review_comments: 'Expired utility bill', uploaded_at: '2026-02-16', reviewed_at: '2026-02-20' },
    { document_id: 'DOC-013', application_id: 'APP-1006', uploaded_by_user_id: 'U010', document_type: 'Passport', file_name: 'linwei_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U004', review_comments: '', uploaded_at: '2026-02-21', reviewed_at: '2026-02-24' },
    { document_id: 'DOC-014', application_id: 'APP-1006', uploaded_by_user_id: 'U010', document_type: 'Address Proof', file_name: 'linwei_address.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U004', review_comments: '', uploaded_at: '2026-02-21', reviewed_at: '2026-02-24' },
    { document_id: 'DOC-015', application_id: 'APP-1007', uploaded_by_user_id: 'U011', document_type: 'Passport', file_name: 'ravi_passport.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: '', uploaded_at: '2026-02-26', reviewed_at: '2026-02-28' },
    { document_id: 'DOC-016', application_id: 'APP-1007', uploaded_by_user_id: 'U011', document_type: 'Director ID', file_name: 'ravi_director.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U002', review_comments: '', uploaded_at: '2026-02-26', reviewed_at: '2026-02-28' },
    { document_id: 'DOC-017', application_id: 'APP-1009', uploaded_by_user_id: 'U005', document_type: 'Passport', file_name: 'ethan_passport2.pdf', file_url: '#', review_status: 'Approved', reviewed_by_user_id: 'U004', review_comments: '', uploaded_at: '2026-03-02', reviewed_at: '2026-03-04' },
    { document_id: 'DOC-018', application_id: 'APP-1009', uploaded_by_user_id: 'U005', document_type: 'Address Proof', file_name: 'ethan_address2.pdf', file_url: '#', review_status: 'Pending', reviewed_by_user_id: null, review_comments: '', uploaded_at: '2026-03-02', reviewed_at: null },
    { document_id: 'DOC-019', application_id: 'APP-1012', uploaded_by_user_id: 'U008', document_type: 'Address Proof', file_name: 'sophia_address2.pdf', file_url: '#', review_status: 'Rejected', reviewed_by_user_id: 'U004', review_comments: 'Invalid — resubmit', uploaded_at: '2026-03-05', reviewed_at: '2026-03-06' },
];

export const STAFF_ASSIGNMENTS = [
    { assignment_id: 'SA-001', application_id: 'APP-1001', staff_user_id: 'U002', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'High priority — fast-track', assigned_at: '2026-01-13', completed_at: null },
    { assignment_id: 'SA-002', application_id: 'APP-1002', staff_user_id: 'U002', assigned_by_admin_id: 'U001', assignment_status: 'Completed', remarks: '', assigned_at: '2026-01-19', completed_at: '2026-02-15' },
    { assignment_id: 'SA-003', application_id: 'APP-1003', staff_user_id: 'U003', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'KYC pending', assigned_at: '2026-02-04', completed_at: null },
    { assignment_id: 'SA-004', application_id: 'APP-1004', staff_user_id: 'U003', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'ACRA submitted', assigned_at: '2026-02-11', completed_at: null },
    { assignment_id: 'SA-005', application_id: 'APP-1005', staff_user_id: 'U004', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'Awaiting docs', assigned_at: '2026-02-16', completed_at: null },
    { assignment_id: 'SA-006', application_id: 'APP-1006', staff_user_id: 'U004', assigned_by_admin_id: 'U001', assignment_status: 'Completed', remarks: '', assigned_at: '2026-02-21', completed_at: '2026-03-08' },
    { assignment_id: 'SA-007', application_id: 'APP-1007', staff_user_id: 'U002', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'EMERGENCY — expedite', assigned_at: '2026-02-26', completed_at: null },
    { assignment_id: 'SA-008', application_id: 'APP-1008', staff_user_id: 'U003', assigned_by_admin_id: 'U001', assignment_status: 'Assigned', remarks: '', assigned_at: '2026-03-05', completed_at: null },
    { assignment_id: 'SA-009', application_id: 'APP-1009', staff_user_id: 'U004', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'KYC under review', assigned_at: '2026-03-02', completed_at: null },
    { assignment_id: 'SA-010', application_id: 'APP-1010', staff_user_id: 'U002', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'ACRA submitted', assigned_at: '2026-03-03', completed_at: null },
    { assignment_id: 'SA-011', application_id: 'APP-1011', staff_user_id: 'U003', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'Finance app — priority', assigned_at: '2026-03-04', completed_at: null },
    { assignment_id: 'SA-012', application_id: 'APP-1012', staff_user_id: 'U004', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: 'KYC rejected — follow up', assigned_at: '2026-03-05', completed_at: null },
    { assignment_id: 'SA-013', application_id: 'APP-1013', staff_user_id: 'U002', assigned_by_admin_id: 'U001', assignment_status: 'Assigned', remarks: 'High value', assigned_at: '2026-03-06', completed_at: null },
    { assignment_id: 'SA-014', application_id: 'APP-1014', staff_user_id: 'U003', assigned_by_admin_id: 'U001', assignment_status: 'In Progress', remarks: '', assigned_at: '2026-03-07', completed_at: null },
    { assignment_id: 'SA-015', application_id: 'APP-1015', staff_user_id: 'U004', assigned_by_admin_id: 'U001', assignment_status: 'Assigned', remarks: '', assigned_at: '2026-03-08', completed_at: null },
];

export const ACRA_SUBMISSIONS_SEED = [
    { acra_submission_id: 'ACRA-S001', application_id: 'APP-1002', submitted_by_user_id: 'U002', submission_type: 'Company Incorporation', submission_reference: 'ACRA-202601-00421', submission_status: 'Approved', submission_date: '2026-02-10', response_date: '2026-02-15', response_message: 'Company successfully incorporated. UEN: 202600421Z', created_at: '2026-02-10', updated_at: '2026-02-15' },
    { acra_submission_id: 'ACRA-S002', application_id: 'APP-1004', submitted_by_user_id: 'U003', submission_type: 'Company Incorporation', submission_reference: 'ACRA-202602-00887', submission_status: 'Submitted', submission_date: '2026-03-04', response_date: null, response_message: '', created_at: '2026-03-04', updated_at: '2026-03-04' },
    { acra_submission_id: 'ACRA-S003', application_id: 'APP-1006', submitted_by_user_id: 'U004', submission_type: 'Company Incorporation', submission_reference: 'ACRA-202602-01103', submission_status: 'Approved', submission_date: '2026-03-01', response_date: '2026-03-08', response_message: 'Company successfully incorporated. UEN: 202601103K', created_at: '2026-03-01', updated_at: '2026-03-08' },
    { acra_submission_id: 'ACRA-S004', application_id: 'APP-1010', submitted_by_user_id: 'U002', submission_type: 'Company Incorporation', submission_reference: 'ACRA-202603-00214', submission_status: 'Submitted', submission_date: '2026-03-08', response_date: null, response_message: '', created_at: '2026-03-08', updated_at: '2026-03-08' },
];

export const NOTIFICATIONS_SEED = [
    { notification_id: 'N001', user_id: 'U001', application_id: 'APP-1001', title: 'New Application ✉️', message: 'Ethan Tan submitted LionPath Trading Pte. Ltd.', notification_type: 'Application Submitted', is_read: true, created_at: '2026-01-12 09:00' },
    { notification_id: 'N002', user_id: 'U002', application_id: 'APP-1001', title: 'New Assignment 📋', message: 'You are assigned to APP-1001: LionPath Trading Pte. Ltd.', notification_type: 'Staff Assigned', is_read: true, created_at: '2026-01-13 09:00' },
    { notification_id: 'N003', user_id: 'U005', application_id: 'APP-1001', title: 'KYC Approved ✅', message: 'Your KYC for LionPath Trading has been approved!', notification_type: 'KYC Approved', is_read: true, created_at: '2026-01-20 14:00' },
    { notification_id: 'N004', user_id: 'U001', application_id: 'APP-1002', title: 'Application Completed 🎉', message: 'Merlion Ventures Pte. Ltd. is now incorporated (ACRA-202601-00421)', notification_type: 'Application Completed', is_read: true, created_at: '2026-02-15 10:00' },
    { notification_id: 'N005', user_id: 'U006', application_id: 'APP-1002', title: '🎉 Company Registered!', message: 'Merlion Ventures Pte. Ltd. is now officially registered with ACRA.', notification_type: 'Application Completed', is_read: true, created_at: '2026-02-15 10:05' },
    { notification_id: 'N006', user_id: 'U001', application_id: 'APP-1003', title: 'New Application ✉️', message: 'Ahmed Hassan submitted Marina Bay Foods Pte. Ltd.', notification_type: 'Application Submitted', is_read: true, created_at: '2026-02-03 11:00' },
    { notification_id: 'N007', user_id: 'U007', application_id: 'APP-1003', title: 'Document Required 📄', message: 'Please reupload a clear Address Proof for Marina Bay Foods.', notification_type: 'Document Required', is_read: false, created_at: '2026-03-06 09:30' },
    { notification_id: 'N008', user_id: 'U001', application_id: 'APP-1004', title: 'Submitted to ACRA 🚀', message: 'SkyBridge Consulting submitted to ACRA. Ref: ACRA-202602-00887', notification_type: 'Submitted to ACRA', is_read: true, created_at: '2026-03-04 15:00' },
    { notification_id: 'N009', user_id: 'U008', application_id: 'APP-1004', title: 'Submitted to ACRA 🚀', message: 'SkyBridge Consulting Pte. Ltd. has been submitted to ACRA for registration.', notification_type: 'Submitted to ACRA', is_read: false, created_at: '2026-03-04 15:05' },
    { notification_id: 'N010', user_id: 'U009', application_id: 'APP-1005', title: 'Document Required 📄', message: 'Your Address Proof for Orchid Bloom Retail was rejected. Please resubmit.', notification_type: 'Document Required', is_read: false, created_at: '2026-02-20 10:00' },
    { notification_id: 'N011', user_id: 'U001', application_id: 'APP-1006', title: 'Application Completed 🎉', message: 'RedDot Ventures Pte. Ltd. incorporated (ACRA-202602-01103)', notification_type: 'Application Completed', is_read: false, created_at: '2026-03-08 11:00' },
    { notification_id: 'N012', user_id: 'U010', application_id: 'APP-1006', title: '🎉 Company Registered!', message: 'RedDot Ventures Pte. Ltd. is now officially incorporated with ACRA. UEN: 202601103K', notification_type: 'Application Completed', is_read: false, created_at: '2026-03-08 11:05' },
    { notification_id: 'N013', user_id: 'U001', application_id: 'APP-1007', title: 'Emergency Application ⚠️', message: 'HarbourEdge Logistics — EMERGENCY priority. Immediate action required.', notification_type: 'Application Submitted', is_read: false, created_at: '2026-02-25 08:00' },
    { notification_id: 'N014', user_id: 'U002', application_id: 'APP-1007', title: 'Emergency Assignment ⚠️', message: 'URGENT: You are assigned to APP-1007 HarbourEdge Logistics — Emergency priority.', notification_type: 'Staff Assigned', is_read: false, created_at: '2026-02-26 08:05' },
    { notification_id: 'N015', user_id: 'U001', application_id: 'APP-1008', title: 'New Application ✉️', message: 'Mei Ling Chua submitted UrbanCore Services Pte. Ltd.', notification_type: 'Application Submitted', is_read: false, created_at: '2026-03-05 10:00' },
    { notification_id: 'N016', user_id: 'U001', application_id: 'APP-1010', title: 'Submitted to ACRA 🚀', message: 'GreenPath Eco submitted to ACRA. Ref: ACRA-202603-00214', notification_type: 'Submitted to ACRA', is_read: false, created_at: '2026-03-08 09:00' },
    { notification_id: 'N017', user_id: 'U006', application_id: 'APP-1010', title: 'Submitted to ACRA 🚀', message: 'GreenPath Eco Pte. Ltd. has been submitted to ACRA awaiting final approval.', notification_type: 'Submitted to ACRA', is_read: false, created_at: '2026-03-08 09:05' },
    { notification_id: 'N018', user_id: 'U008', application_id: 'APP-1012', title: 'KYC Rejected ❌', message: 'Your KYC for NovaMed Health — address proof invalid. Please resubmit.', notification_type: 'Document Required', is_read: false, created_at: '2026-03-06 14:00' },
    { notification_id: 'N019', user_id: 'U001', application_id: 'APP-1013', title: 'New Application ✉️', message: 'Marcus Ng submitted CityScape Properties (SGD 200,000 share capital)', notification_type: 'Application Submitted', is_read: false, created_at: '2026-03-06 12:00' },
    { notification_id: 'N020', user_id: 'U011', application_id: 'APP-1011', title: 'Application In Progress 🔄', message: 'AsiaLink Finance Pte. Ltd. is now being processed by our team.', notification_type: 'Status Changed', is_read: false, created_at: '2026-03-07 10:00' },
];

export const ACTIVITY_LOGS_SEED = [
    { log_id: 'L001', user_id: 'U005', application_id: 'APP-1001', action_type: 'Application Created', action_description: 'Ethan Tan submitted LionPath Trading Pte. Ltd.', old_value: null, new_value: { status: 'New' }, created_at: '2026-01-12 09:00' },
    { log_id: 'L002', user_id: 'U001', application_id: 'APP-1001', action_type: 'Staff Assigned', action_description: 'Sarah Lim assigned to APP-1001', old_value: null, new_value: { staff: 'U002' }, created_at: '2026-01-13 09:00' },
    { log_id: 'L003', user_id: 'U002', application_id: 'APP-1001', action_type: 'Status Updated', action_description: 'New → KYC Review', old_value: { status: 'New' }, new_value: { status: 'KYC Review' }, created_at: '2026-01-14 10:00' },
    { log_id: 'L004', user_id: 'U002', application_id: 'APP-1001', action_type: 'KYC Approved', action_description: 'KYC approved — advanced to In Progress', old_value: { kyc: 'Under Review' }, new_value: { kyc: 'Approved' }, created_at: '2026-01-20 14:00' },
    { log_id: 'L005', user_id: 'U006', application_id: 'APP-1002', action_type: 'Application Created', action_description: 'Priya Sharma submitted Merlion Ventures Pte. Ltd.', old_value: null, new_value: { status: 'New' }, created_at: '2026-01-18 10:00' },
    { log_id: 'L006', user_id: 'U002', application_id: 'APP-1002', action_type: 'KYC Approved', action_description: 'KYC approved for Merlion Ventures', old_value: { kyc: 'Under Review' }, new_value: { kyc: 'Approved' }, created_at: '2026-01-25 11:00' },
    { log_id: 'L007', user_id: 'U002', application_id: 'APP-1002', action_type: 'ACRA Submitted', action_description: 'Submitted to ACRA. Ref: ACRA-202601-00421', old_value: { status: 'In Progress' }, new_value: { status: 'Submitted to ACRA' }, created_at: '2026-02-10 14:00' },
    { log_id: 'L008', user_id: 'U001', application_id: 'APP-1002', action_type: 'Application Completed', action_description: 'Merlion Ventures incorporated. UEN: 202600421Z', old_value: { status: 'Submitted to ACRA' }, new_value: { status: 'Completed' }, created_at: '2026-02-15 10:00' },
    { log_id: 'L009', user_id: 'U007', application_id: 'APP-1003', action_type: 'Application Created', action_description: 'Ahmed Hassan submitted Marina Bay Foods Pte. Ltd.', old_value: null, new_value: { status: 'New' }, created_at: '2026-02-03 11:00' },
    { log_id: 'L010', user_id: 'U003', application_id: 'APP-1003', action_type: 'Status Updated', action_description: 'New → KYC Review', old_value: { status: 'New' }, new_value: { status: 'KYC Review' }, created_at: '2026-02-05 09:00' },
    { log_id: 'L011', user_id: 'U003', application_id: 'APP-1003', action_type: 'Document Reviewed', action_description: 'Address Proof marked Pending — blurry scan', old_value: { status: 'Pending' }, new_value: { status: 'Pending' }, created_at: '2026-03-06 09:30' },
    { log_id: 'L012', user_id: 'U003', application_id: 'APP-1004', action_type: 'ACRA Submitted', action_description: 'Submitted to ACRA. Ref: ACRA-202602-00887', old_value: { status: 'In Progress' }, new_value: { status: 'Submitted to ACRA' }, created_at: '2026-03-04 15:00' },
    { log_id: 'L013', user_id: 'U004', application_id: 'APP-1005', action_type: 'Document Reviewed', action_description: 'Address Proof rejected — expired utility bill', old_value: { status: 'Pending' }, new_value: { status: 'Rejected' }, created_at: '2026-02-20 10:00' },
    { log_id: 'L014', user_id: 'U004', application_id: 'APP-1006', action_type: 'ACRA Submitted', action_description: 'Submitted to ACRA. Ref: ACRA-202602-01103', old_value: { status: 'In Progress' }, new_value: { status: 'Submitted to ACRA' }, created_at: '2026-03-01 14:00' },
    { log_id: 'L015', user_id: 'U001', application_id: 'APP-1006', action_type: 'Application Completed', action_description: 'RedDot Ventures incorporated. UEN: 202601103K', old_value: { status: 'Submitted to ACRA' }, new_value: { status: 'Completed' }, created_at: '2026-03-08 11:00' },
    { log_id: 'L016', user_id: 'U002', application_id: 'APP-1007', action_type: 'Status Updated', action_description: 'New → In Progress (EMERGENCY)', old_value: { status: 'New' }, new_value: { status: 'In Progress' }, created_at: '2026-02-26 09:00' },
    { log_id: 'L017', user_id: 'U004', application_id: 'APP-1009', action_type: 'Status Updated', action_description: 'New → KYC Review', old_value: { status: 'New' }, new_value: { status: 'KYC Review' }, created_at: '2026-03-03 10:00' },
    { log_id: 'L018', user_id: 'U002', application_id: 'APP-1010', action_type: 'ACRA Submitted', action_description: 'Submitted to ACRA. Ref: ACRA-202603-00214', old_value: { status: 'In Progress' }, new_value: { status: 'Submitted to ACRA' }, created_at: '2026-03-08 09:00' },
    { log_id: 'L019', user_id: 'U004', application_id: 'APP-1012', action_type: 'KYC Rejected', action_description: 'Address proof invalid — client notified to resubmit', old_value: { kyc: 'Under Review' }, new_value: { kyc: 'Rejected' }, created_at: '2026-03-06 14:00' },
    { log_id: 'L020', user_id: 'U003', application_id: 'APP-1011', action_type: 'Status Updated', action_description: 'KYC Review → In Progress', old_value: { status: 'KYC Review' }, new_value: { status: 'In Progress' }, created_at: '2026-03-07 10:00' },
];

export const FOLLOWUPS_SEED = [
    { followup_id: 'F001', application_id: 'APP-1001', created_by_user_id: 'U002', assigned_to_user_id: 'U005', followup_type: 'Document Request', due_date: '2026-03-15', status: 'Open', notes: 'Director ID still pending — please upload NRIC or passport copy', resolution_notes: '', created_at: '2026-03-05', updated_at: '2026-03-05' },
    { followup_id: 'F002', application_id: 'APP-1003', created_by_user_id: 'U003', assigned_to_user_id: 'U007', followup_type: 'Document Request', due_date: '2026-03-12', status: 'Open', notes: 'Address proof scan is blurry — reupload required', resolution_notes: '', created_at: '2026-03-06', updated_at: '2026-03-06' },
    { followup_id: 'F003', application_id: 'APP-1005', created_by_user_id: 'U004', assigned_to_user_id: 'U009', followup_type: 'Document Request', due_date: '2026-03-11', status: 'Open', notes: 'Expired utility bill rejected — submit valid address proof dated within 3 months', resolution_notes: '', created_at: '2026-02-20', updated_at: '2026-02-20' },
    { followup_id: 'F004', application_id: 'APP-1007', created_by_user_id: 'U002', assigned_to_user_id: 'U011', followup_type: 'KYC Clarification', due_date: '2026-03-10', status: 'Open', notes: 'Emergency case — confirm shareholder details immediately', resolution_notes: '', created_at: '2026-03-01', updated_at: '2026-03-01' },
    { followup_id: 'F005', application_id: 'APP-1009', created_by_user_id: 'U004', assigned_to_user_id: 'U005', followup_type: 'KYC Clarification', due_date: '2026-03-13', status: 'Open', notes: 'Director ID scan unclear — submit high-resolution copy', resolution_notes: '', created_at: '2026-03-08', updated_at: '2026-03-08' },
    { followup_id: 'F006', application_id: 'APP-1012', created_by_user_id: 'U004', assigned_to_user_id: 'U008', followup_type: 'Document Request', due_date: '2026-03-12', status: 'Open', notes: 'KYC rejected — address proof invalid. Provide valid proof of residential address.', resolution_notes: '', created_at: '2026-03-06', updated_at: '2026-03-06' },
    { followup_id: 'F007', application_id: 'APP-1002', created_by_user_id: 'U002', assigned_to_user_id: 'U002', followup_type: 'Internal Review', due_date: '2026-02-14', status: 'Closed', notes: 'Final check before ACRA submission', resolution_notes: 'All verified — submitted to ACRA', created_at: '2026-02-13', updated_at: '2026-02-15' },
];

export const COMPANIES = [
    {
        company_id: 'C001',
        application_id: 'APP-1002',
        client_user_id: 'U006',
        name: 'Merlion Ventures Pte. Ltd.',
        uen: '202600421Z',
        incorporation_date: '2026-02-15',
        status: 'Live',
        registered_address: '1 Raffles Place #20-01, Singapore 048616',
        share_capital: 50000,
        share_currency: 'SGD',
        compliance_status: 'Compliant',
    },
    {
        company_id: 'C002',
        application_id: 'APP-1006',
        client_user_id: 'U010',
        name: 'RedDot Ventures Pte. Ltd.',
        uen: '202601103K',
        incorporation_date: '2026-03-08',
        status: 'Live',
        registered_address: '79 Anson Road #23-01, Singapore 079906',
        share_capital: 100000,
        share_currency: 'SGD',
        compliance_status: 'Action Required',
    },
];

export const DIRECTORS = [
    { director_id: 'D001', company_id: 'C001', name: 'Priya Sharma', nationality: 'Indian', appointed_date: '2026-02-15', status: 'Active' },
    { director_id: 'D002', company_id: 'C001', name: 'Sarah Lim', nationality: 'Singaporean', appointed_date: '2026-02-15', status: 'Active' },
    { director_id: 'D003', company_id: 'C002', name: 'Lin Wei', nationality: 'Singaporean', appointed_date: '2026-03-08', status: 'Active' },
];

export const SHAREHOLDERS = [
    { shareholder_id: 'S001', company_id: 'C001', name: 'Priya Sharma', shares: 40000, percentage: '80%' },
    { shareholder_id: 'S002', company_id: 'C001', name: 'Advent Global Ltd.', shares: 10000, percentage: '20%' },
    { shareholder_id: 'S003', company_id: 'C002', name: 'Lin Wei', shares: 100000, percentage: '100%' },
];

export const COMPLIANCE_EVENTS = [
    { event_id: 'CE001', company_id: 'C001', type: 'Annual Return Filing', deadline: '2027-02-15', status: 'Upcoming' },
    { event_id: 'CE002', company_id: 'C001', type: 'Director KYC Renewal', deadline: '2026-08-15', status: 'Upcoming' },
    { event_id: 'CE003', company_id: 'C002', type: 'Annual Return Filing', deadline: '2027-03-08', status: 'Upcoming' },
    { event_id: 'CE004', company_id: 'C002', type: 'Corporate Secretary Renewal', deadline: '2026-04-08', status: 'Urgent' },
];

export const VAULT_DOCUMENTS = [
    { doc_id: 'V001', company_id: 'C001', type: 'Certificate of Incorporation', name: 'Inc_Cert_Merlion.pdf', version: '1.0', added_at: '2026-02-15' },
    { doc_id: 'V002', company_id: 'C001', type: 'ACRA Business Profile', name: 'Biz_Profile_Merlion_Feb26.pdf', version: '1.1', added_at: '2026-02-16' },
    { doc_id: 'V003', company_id: 'C002', type: 'Certificate of Incorporation', name: 'Inc_Cert_RedDot.pdf', version: '1.0', added_at: '2026-03-08' },
];
